export type Entity = 'lots' | 'tasks' | 'applications' | 'stock' | 'irrigation' | 'monitoring'
export type Row = { id: string; [key: string]: string }
export type Field = { key: string; label: string; type?: 'number' | 'date'; options?: string[] }
const field = (key: string, label: string, type?: Field['type']): Field => ({ key, label, type })
const select = (key: string, label: string, options: string[]): Field => ({ key, label, options })
const lot = field('lot', 'Lote')
const date = field('date', 'Fecha', 'date')
const responsible = field('responsible', 'Responsable')
const notes = field('notes', 'Observaciones')
export const definitions: Record<Entity, { title: string; action: string; fields: Field[] }> = {
  lots: {
    title: 'Lotes y cultivos',
    action: 'Nuevo lote',
    fields: [
      field('name', 'Nombre del lote'),
      select('crop', 'Cultivo', ['Arroz', 'Maíz', 'Soja']),
      field('variety', 'Variedad'),
      field('area', 'Superficie (ha)', 'number'),
      field('date', 'Fecha de siembra', 'date'),
      field('stage', 'Etapa fenológica'),
      select('status', 'Estado', ['Normal', 'Revisar']),
      field('location', 'Ubicación'),
      notes,
    ],
  },
  tasks: {
    title: 'Agenda de tareas',
    action: 'Nueva tarea',
    fields: [
      field('title', 'Título'),
      select('type', 'Tipo', [
        'Siembra',
        'Fertilización',
        'Fumigación',
        'Riego',
        'Monitoreo',
        'Cosecha',
        'Mantenimiento',
      ]),
      lot,
      date,
      responsible,
      select('priority', 'Prioridad', ['Media', 'Alta', 'Baja']),
      select('status', 'Estado', ['Pendiente', 'En curso', 'Completada', 'Atrasada']),
      notes,
    ],
  },
  applications: {
    title: 'Historial de aplicaciones',
    action: 'Registrar aplicación',
    fields: [
      lot,
      field('product', 'Producto'),
      select('type', 'Tipo de insumo', [
        'Fertilizante',
        'Herbicida',
        'Insecticida',
        'Fungicida',
        'Otro',
      ]),
      field('dose', 'Dosis', 'number'),
      field('unit', 'Unidad'),
      field('area', 'Superficie aplicada (ha)', 'number'),
      date,
      responsible,
      notes,
    ],
  },
  stock: {
    title: 'Inventario de insumos',
    action: 'Nuevo insumo',
    fields: [
      field('name', 'Nombre'),
      select('category', 'Categoría', [
        'Semillas',
        'Fertilizantes',
        'Herbicidas',
        'Insecticidas',
        'Fungicidas',
        'Otros',
      ]),
      field('quantity', 'Cantidad disponible', 'number'),
      field('unit', 'Unidad'),
      field('minimum', 'Stock mínimo', 'number'),
      field('location', 'Ubicación'),
      field('supplier', 'Proveedor'),
      notes,
    ],
  },
  irrigation: {
    title: 'Historial de riegos',
    action: 'Registrar riego',
    fields: [
      lot,
      date,
      field('duration', 'Duración (horas)', 'number'),
      field('amount', 'Cantidad estimada (m³)', 'number'),
      select('method', 'Método', ['Inundación', 'Aspersión', 'Goteo']),
      responsible,
      field('next', 'Próximo riego', 'date'),
      notes,
    ],
  },
  monitoring: {
    title: 'Historial de monitoreos',
    action: 'Registrar monitoreo',
    fields: [
      lot,
      date,
      field('humidity', 'Humedad del suelo (%)', 'number'),
      field('pests', 'Plagas'),
      field('weeds', 'Malezas'),
      field('diseases', 'Enfermedades'),
      select('status', 'Estado general', ['Normal', 'Revisar']),
      notes,
    ],
  },
}
export const initialData: Record<Entity, Row[]> = {
  lots: [
    {
      id: 'l1',
      name: 'Lote Norte',
      crop: 'Arroz',
      variety: 'IRGA 424',
      area: '42.5',
      date: '2026-09-01',
      stage: 'Macollaje',
      status: 'Normal',
      location: 'Mercedes, Corrientes',
      notes: 'Lámina de agua uniforme.',
    },
    {
      id: 'l2',
      name: 'Lote Sur',
      crop: 'Maíz',
      variety: 'DK72',
      area: '31.2',
      date: '2026-08-25',
      stage: 'V6',
      status: 'Revisar',
      location: 'Curuzú Cuatiá, Corrientes',
      notes: 'Revisar presencia de malezas en cabecera.',
    },
    {
      id: 'l3',
      name: 'Lote Este',
      crop: 'Soja',
      variety: 'DM 46i20',
      area: '28',
      date: '2026-09-10',
      stage: 'V2',
      status: 'Normal',
      location: 'Mercedes, Corrientes',
      notes: 'Implantación uniforme. Escenario ilustrativo.',
    },
  ],
  tasks: [
    {
      id: 't1',
      title: 'Fertilizar Lote Norte',
      type: 'Fertilización',
      lot: 'Lote Norte',
      date: '2026-10-02',
      responsible: 'Martín López',
      priority: 'Alta',
      status: 'Pendiente',
      notes: 'Verificar disponibilidad de insumos.',
    },
    {
      id: 't2',
      title: 'Fumigar Lote Sur',
      type: 'Fumigación',
      lot: 'Lote Sur',
      date: '2026-10-03',
      responsible: 'Lucía Gómez',
      priority: 'Alta',
      status: 'Pendiente',
      notes: 'Sujeto a evaluación técnica.',
    },
    {
      id: 't3',
      title: 'Revisar riego',
      type: 'Riego',
      lot: 'Lote Norte',
      date: '2026-10-01',
      responsible: 'Pedro Silva',
      priority: 'Media',
      status: 'En curso',
      notes: 'Control de compuertas.',
    },
    {
      id: 't4',
      title: 'Monitorear malezas',
      type: 'Monitoreo',
      lot: 'Lote Sur',
      date: '2026-09-30',
      responsible: 'Lucía Gómez',
      priority: 'Alta',
      status: 'Atrasada',
      notes: 'Recorrer cabecera sur.',
    },
  ],
  applications: [
    {
      id: 'a1',
      lot: 'Lote Norte',
      product: 'Urea granulada',
      type: 'Fertilizante',
      dose: '80',
      unit: 'kg/ha',
      area: '42.5',
      date: '2026-10-01',
      responsible: 'Martín López',
      notes: 'Registro ficticio, no es una recomendación de aplicación.',
    },
    {
      id: 'a2',
      lot: 'Lote Sur',
      product: 'Fertilizante MAP',
      type: 'Fertilizante',
      dose: '60',
      unit: 'kg/ha',
      area: '31.2',
      date: '2026-09-20',
      responsible: 'Lucía Gómez',
      notes: 'Registro demostrativo de campaña.',
    },
  ],
  stock: [
    {
      id: 's1',
      name: 'Urea granulada',
      category: 'Fertilizantes',
      quantity: '450',
      unit: 'kg',
      minimum: '600',
      location: 'Galpón Mercedes',
      supplier: 'Cooperativa local',
      notes: 'Programar reposición.',
    },
    {
      id: 's2',
      name: 'Semilla IRGA 424',
      category: 'Semillas',
      quantity: '1800',
      unit: 'kg',
      minimum: '500',
      location: 'Depósito central',
      supplier: 'Semillero Corrientes',
      notes: 'Bolsas cerradas.',
    },
    {
      id: 's3',
      name: 'Herbicida selectivo',
      category: 'Herbicidas',
      quantity: '0',
      unit: 'L',
      minimum: '40',
      location: 'Depósito de insumos',
      supplier: 'Agroinsumos del Litoral',
      notes: 'Reposición pendiente.',
    },
    {
      id: 's4',
      name: 'Insecticida agrícola',
      category: 'Insecticidas',
      quantity: '65',
      unit: 'L',
      minimum: '20',
      location: 'Depósito de insumos',
      supplier: 'Agroinsumos del Litoral',
      notes: 'Inventario de demostración.',
    },
  ],
  irrigation: [
    {
      id: 'r1',
      lot: 'Lote Norte',
      date: '2026-09-30',
      duration: '8',
      amount: '3400',
      method: 'Inundación',
      responsible: 'Pedro Silva',
      next: '2026-10-02',
      notes: 'Controlar nivel de lámina.',
    },
    {
      id: 'r2',
      lot: 'Lote Sur',
      date: '2026-09-29',
      duration: '3',
      amount: '780',
      method: 'Aspersión',
      responsible: 'Pedro Silva',
      next: '2026-10-04',
      notes: 'Revisar humedad antes del próximo turno.',
    },
  ],
  monitoring: [
    {
      id: 'm1',
      lot: 'Lote Norte',
      date: '2026-10-01',
      humidity: '78',
      pests: 'Sin presencia',
      weeds: 'Baja presencia',
      diseases: 'Sin síntomas',
      status: 'Normal',
      notes: 'Buena uniformidad del cultivo.',
    },
    {
      id: 'm2',
      lot: 'Lote Sur',
      date: '2026-10-01',
      humidity: '34',
      pests: 'Baja presencia',
      weeds: 'Presencia en cabecera',
      diseases: 'Sin síntomas',
      status: 'Revisar',
      notes: 'Programar recorrida de seguimiento.',
    },
  ],
}
export function stockStatus(row: Row) {
  return Number(row['quantity']) === 0
    ? 'Sin stock'
    : Number(row['quantity']) < Number(row['minimum'])
      ? 'Stock bajo'
      : 'Stock normal'
}
export function formatDate(value: string | undefined) {
  return value ? value.split('-').reverse().join('/') : '—'
}
